"""Export: rebuild the (possibly edited) paper as a LaTeX project.

The zip contains:
  main.tex        — structure + sections; citation tokens become \\cite
                    commands; bibliography is a thebibliography whose entry
                    TEXT is citeproc-rendered in the selected CSL style
                    (all citation formatting flows through CSL, no string
                    templates)
  references.bib  — the canonical CSL-JSON serialized to BibTeX, for users
                    who prefer a bibtex toolchain
  paper.md        — the same document rendered to Markdown with formatted
                    inline labels (handy for diffing)
  paper.json      — the full canonical document (sections with tokens,
                    references as CSL-JSON, parse report, version history)
  PROVENANCE.md   — where every agent-added citation came from + the edit
                    history, so nothing about the revision is opaque
"""
from __future__ import annotations

import io
import json
import re
import time
import zipfile

from ..cslproc.render import DocumentRenderer, renderable
from ..models.core import CITE_TOKEN_RE, FloatKind, PaperDocument, SectionKind
from .bibtex import bibliography_to_bibtex

_TEX_SPECIALS = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}


def _tex_escape(s: str) -> str:
    for k, v in _TEX_SPECIALS.items():
        s = s.replace(k, v)
    return s


def _tex_body(text: str, author_year: bool) -> str:
    """Escape prose for LaTeX while turning citation tokens into \\cite
    commands. Tokens are shielded from escaping via placeholders (escaping
    first would mangle the ``ref_N`` keys)."""
    shields: list[str] = []

    def shield(m: re.Match) -> str:
        kind = m.group(1)
        ids = ",".join(r.strip() for r in m.group(2).split(",") if r.strip())
        if author_year:
            cmd = (r"\citet{" if kind == "t" else r"\citep{") + ids + "}"
        else:
            cmd = r"\cite{" + ids + "}"
        shields.append(cmd)
        return f"\x00{len(shields) - 1}\x00"

    text = CITE_TOKEN_RE.sub(shield, text)
    text = _tex_escape(text)
    for i, cmd in enumerate(shields):
        text = text.replace(f"\x00{i}\x00", cmd)
    return text


def build_latex(doc: PaperDocument, style_id: str | None = None) -> dict[str, str]:
    style_id = style_id or doc.csl_style
    rend = DocumentRenderer(doc, style_id)
    author_year = rend.author_year

    lines: list[str] = []
    lines.append("% Generated by Paper Improvement Agent")
    lines.append(f"% Citation style: {style_id} (CSL); "
                 f"bibliography text rendered by citeproc")
    lines.append(r"\documentclass[11pt]{article}")
    lines.append(r"\usepackage[utf8]{inputenc}")
    if author_year:
        lines.append(r"\usepackage[round]{natbib}")
    else:
        lines.append(r"\usepackage{cite}")
    lines.append(r"\usepackage[margin=1in]{geometry}")
    lines.append(rf"\title{{{_tex_escape(doc.meta.title)}}}")
    authors = " \\and ".join(_tex_escape(a) for a in doc.meta.authors) or "~"
    lines.append(rf"\author{{{authors}}}")
    lines.append(r"\date{}")
    lines.append(r"\begin{document}")
    lines.append(r"\maketitle")

    floats_by_section: dict[str, list] = {}
    for fl in doc.floats:
        floats_by_section.setdefault(fl.section_id or "", []).append(fl)
    emitted: set[str] = set()

    for sec in doc.sections:
        if sec.kind == SectionKind.REFERENCES:
            continue
        body = _tex_body(sec.content, author_year)
        body = re.sub(r"\n\n+", "\n\n", body)
        if sec.kind == SectionKind.ABSTRACT:
            lines.append(r"\begin{abstract}")
            lines.append(re.sub(r"^abstract\s*[—\-–\.:]?\s*", "", body, flags=re.I))
            lines.append(r"\end{abstract}")
            continue
        cmd = {1: r"\section", 2: r"\subsection", 3: r"\subsubsection"}.get(
            min(sec.level, 3), r"\subsubsection")
        lines.append(f"{cmd}{{{_tex_escape(sec.title)}}}")
        if body.strip():
            lines.append(body)
        for fl in floats_by_section.get(sec.id, []):
            lines.extend(_tex_float(fl, author_year))
            emitted.add(fl.id)

    # Any float not emitted above still ships: its anchor section was
    # unknown, or was a section the exporter skips (e.g. References).
    # Dropping it would silently lose text the parser deliberately kept.
    leftover = [f for f in doc.floats if f.id not in emitted]
    if leftover:
        lines.append(r"\section*{Unanchored floats}")
        lines.append("% Captured from the PDF but not attachable to an exported "
                     "section; text preserved here rather than dropped.")
        for fl in leftover:
            lines.extend(_tex_float(fl, author_year))

    # ---- bibliography: citeproc-rendered text, CSL-ordered -------------
    bib = rend.bibliography()
    lines.append("")
    lines.append(r"\begin{thebibliography}{" + str(max(9, len(bib))) + "}")
    ref_by_id = {r.id: r for r in doc.references}
    for entry in bib:
        ref = ref_by_id.get(entry["ref_id"])
        label = ""
        if author_year and ref is not None:
            label = "[" + _natbib_label(ref) + "]"
        text = entry["formatted"]
        # numeric styles include their own "[3]"-style prefix — strip it,
        # thebibliography numbers items itself
        text = re.sub(r"^\s*\[?\d+\]?\.?\s*", "", text) if not author_year else text
        marker = "  % UNPARSED — raw text kept verbatim" if entry["raw_fallback"] else ""
        lines.append(rf"\bibitem{label}{{{entry['ref_id']}}} {_tex_escape(text)}{marker}")
    lines.append(r"\end{thebibliography}")
    lines.append(r"\end{document}")

    main_tex = "\n".join(lines) + "\n"
    bib_items = [r.csl for r in doc.references if renderable(r)]
    return {
        "main.tex": main_tex,
        "references.bib": bibliography_to_bibtex(bib_items),
        "paper.md": build_markdown(doc, style_id),
        "paper.json": doc.model_dump_json(indent=2),
        "PROVENANCE.md": build_provenance(doc),
    }


def _tex_float(fl, author_year: bool) -> list[str]:
    """A captured float as a LaTeX environment.

    The parser preserves a float's *text*, not its visual layout, so the
    emitted environment says so in a comment rather than pretending to
    reconstruct a figure. A ruled table's cells survive as a tabular-ish
    verbatim block: honest, and editable by hand downstream.
    """
    env = {FloatKind.TABLE: "table", FloatKind.FIGURE: "figure"}.get(fl.kind)
    out: list[str] = []
    body = _tex_body(fl.text, author_year).strip()
    caption = _tex_escape(fl.caption).strip()
    if env is None:                       # boxed panel — no float environment
        out.append(r"\begin{quote}")
        out.append(f"% {fl.id}: boxed panel captured from page {fl.page + 1}; "
                   "text preserved, original framing not reconstructed")
        if caption:
            out.append(rf"\textbf{{{caption}}}")
        out.append(body)
        out.append(r"\end{quote}")
        return out
    out.append(rf"\begin{{{env}}}[htbp]")
    out.append(f"% {fl.id}: {fl.kind.value} captured from page {fl.page + 1}; "
               "text preserved, visual layout not reconstructed")
    out.append(r"\centering")
    if body:
        out.append(body)
    if caption:
        out.append(rf"\caption{{{caption}}}")
    out.append(rf"\end{{{env}}}")
    return out


def _natbib_label(ref) -> str:
    fams = [a.split(",")[0].strip() for a in ref.parsed.authors[:3]]
    year = ref.parsed.year or "n.d."
    if not fams:
        fams = [str(ref.csl.get("title", ref.id))[:20]]
    if len(fams) == 1:
        name = fams[0]
    elif len(fams) == 2:
        name = f"{fams[0]} and {fams[1]}"
    else:
        name = f"{fams[0]} et al."
    return f"{name}({year})"


def build_markdown(doc: PaperDocument, style_id: str | None = None) -> str:
    rend = DocumentRenderer(doc, style_id or doc.csl_style)
    out = [f"# {doc.meta.title}", ""]
    md_emitted: set[str] = set()
    if doc.meta.authors:
        out += [", ".join(doc.meta.authors), ""]
    for sec in doc.sections:
        if sec.kind == SectionKind.REFERENCES:
            continue
        out.append(("#" * min(sec.level + 1, 4)) + " " + sec.title)
        out.append("")
        if sec.content.strip():
            out.append(rend.render_text(sec.content))
            out.append("")
        for fl in doc.floats:
            if fl.section_id != sec.id:
                continue
            md_emitted.add(fl.id)
            label = fl.caption or f"{fl.kind.value.title()} (page {fl.page + 1})"
            out.append(f"> **{label}**")
            out.append(">")
            for para in fl.text.split("\n\n"):
                out.append("> " + para.replace("\n", "\n> "))
                out.append(">")
            out.append("> _text preserved; original layout not reconstructed_")
            out.append("")
    leftover = [f for f in doc.floats if f.id not in md_emitted]
    if leftover:
        out.append("## Unanchored floats")
        out.append("")
        for fl in leftover:
            label = fl.caption or f"{fl.kind.value.title()} (page {fl.page + 1})"
            out.append(f"> **{label}**")
            out.append(">")
            for para in fl.text.split("\n\n"):
                out.append("> " + para.replace("\n", "\n> "))
                out.append(">")
            out.append("")
    out.append("## References")
    out.append("")
    for entry in rend.bibliography():
        suffix = "  ⚠ unparsed (raw text)" if entry["raw_fallback"] else ""
        out.append(f"- {entry['formatted']}{suffix}")
    return "\n".join(out) + "\n"


def build_provenance(doc: PaperDocument) -> str:
    out = ["# Provenance", "",
           f"Paper: {doc.meta.title}",
           f"Version: {doc.version}", ""]
    agent_refs = [r for r in doc.references if r.added_by == "agent"]
    out.append(f"## Agent-added references ({len(agent_refs)})")
    out.append("")
    for r in agent_refs:
        out.append(f"- **{r.csl.get('title', '?')}** — added because: "
                   f"{r.added_reason or '?'}")
        out.append(f"  - source: {r.resolution.source} — {r.resolution.source_url}")
    if not agent_refs:
        out.append("(none)")
    out.append("")
    out.append("## Edit history")
    out.append("")
    for v in doc.history:
        out.append(f"- v{v.version} → v{v.version + 1}: {v.reason} "
                   f"({time.strftime('%Y-%m-%d %H:%M', time.localtime(v.created_at))})")
    if not doc.history:
        out.append("(no edits applied — original parse)")
    return "\n".join(out) + "\n"


def build_zip(doc: PaperDocument, style_id: str | None = None) -> bytes:
    files = build_latex(doc, style_id)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name, content in files.items():
            z.writestr(name, content)
    return buf.getvalue()


def parse_report_json(doc: PaperDocument) -> str:
    return json.dumps(doc.parse_report.model_dump(), indent=2)
